/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.objecteditors.wunda_blau;

import Sirius.server.middleware.types.MetaClass;

import com.vividsolutions.jts.geom.Point;

import org.apache.log4j.Logger;

import org.openide.util.Exceptions;

import de.cismet.cids.custom.objectrenderer.utils.CidsBeanSupport;
import de.cismet.cids.custom.objectrenderer.utils.DefaultPreviewMapPanel;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.Disposable;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

import de.cismet.cismap.commons.BoundingBox;
import de.cismet.cismap.commons.CrsTransformer;
import de.cismet.cismap.commons.interaction.CismapBroker;

import de.cismet.connectioncontext.ConnectionContext;
import de.cismet.tools.gui.RoundedPanel;
import de.cismet.tools.gui.SemiRoundedPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import lombok.Getter;
import lombok.Setter;
import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

/**
 * DOCUMENT ME!
 *
 * @author   sandra
 * @version  $Revision$, $Date$ Vorschau der Geometrie wird an einem Ort gesteuert
 */
public class CustomLagePanel extends javax.swing.JPanel implements Disposable {

    //~ Static fields/initializers ---------------------------------------------

    private static final Logger LOG = Logger.getLogger(CustomLagePanel.class);
    public static final String FIELD__ID = "id";
    public static final String FIELD__GEO_FIELD = "geo_field"; // geom
    @Getter@Setter private static String fieldGeoreferenzGeoField;
    public static final String TABLE_GEOM = "geom";
    public String titleKarte = "Lage";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLabel lblKarte;
    JPanel panContent;
    JPanel panGeometrie;
    JPanel panLage;
    DefaultPreviewMapPanel panPreviewMap;
    RoundedPanel rpKarte;
    SemiRoundedPanel semiRoundedPanel7;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    
    /**
     * Creates a new CustomLagePanel object.
     */
    public CustomLagePanel() {
        panPreviewMap = new DefaultPreviewMapPanel();
        initComponents();
        lblKarte.setText(titleKarte);
    }
    
    

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        panContent = new JPanel();
        panGeometrie = new JPanel();
        panLage = new JPanel();
        rpKarte = new RoundedPanel();
        panPreviewMap = new DefaultPreviewMapPanel();
        semiRoundedPanel7 = new SemiRoundedPanel();
        lblKarte = new JLabel();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new GridBagLayout());

        panContent.setName(""); // NOI18N
        panContent.setOpaque(false);
        panContent.setPreferredSize(new Dimension(205, 400));
        panContent.setLayout(new GridBagLayout());

        panGeometrie.setMinimumSize(new Dimension(50, 200));
        panGeometrie.setName("panGeometrie"); // NOI18N
        panGeometrie.setOpaque(false);
        panGeometrie.setLayout(new GridBagLayout());

        panLage.setName("panLage"); // NOI18N
        panLage.setOpaque(false);
        panLage.setLayout(new GridBagLayout());

        rpKarte.setName(""); // NOI18N
        rpKarte.setLayout(new GridBagLayout());

        panPreviewMap.setName("panPreviewMap"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        rpKarte.add(panPreviewMap, gridBagConstraints);

        semiRoundedPanel7.setBackground(Color.darkGray);
        semiRoundedPanel7.setName("semiRoundedPanel7"); // NOI18N
        semiRoundedPanel7.setLayout(new GridBagLayout());

        lblKarte.setForeground(new Color(255, 255, 255));
        Mnemonics.setLocalizedText(lblKarte, NbBundle.getMessage(CustomLagePanel.class, "CustomLagePanel.lblKarte.text")); // NOI18N
        lblKarte.setName("lblKarte"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(5, 10, 5, 5);
        semiRoundedPanel7.add(lblKarte, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        rpKarte.add(semiRoundedPanel7, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panLage.add(rpKarte, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panGeometrie.add(panLage, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(5, 0, 0, 2);
        panContent.add(panGeometrie, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panContent, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void dispose() {
        if (panPreviewMap != null) {
            panPreviewMap.dispose();
        }
    }

    public void setTitleKarte(String title){
        lblKarte.setText(title);
    } 
    /**
     * DOCUMENT ME!
     *
     * @param  cidsBean           DOCUMENT ME!
     * @param  connectionContext  DOCUMENT ME!
     * @param  mapCallString      DOCUMENT ME!
     * @param buffer
     * @param geoField
     */
    public void setMapWindow(final CidsBean cidsBean,
            final ConnectionContext connectionContext,
            final String mapCallString,
            final double buffer,
            final String geoField) {
        setFieldGeoreferenzGeoField(geoField + ".geo_field");
        if (cidsBean != null) {
            try {
                if (cidsBean.getProperty(geoField) != null) {
                    panPreviewMap.initMap(cidsBean, getFieldGeoreferenzGeoField(), buffer, mapCallString);
                } else {
                    if (cidsBean.getProperty(FIELD__GEO_FIELD) != null) {
                        panPreviewMap.initMap(cidsBean, FIELD__GEO_FIELD, buffer, mapCallString);
                    } else {
                        final CidsBean newGeom = createDefaultGeom(connectionContext);
                        panPreviewMap.initMap(newGeom, FIELD__GEO_FIELD, buffer, mapCallString);
                    }
                }
            } catch (final Exception ex) {
                LOG.warn("Map window not set.", ex);
            }
        } else {
            final CidsBean newGeom = createDefaultGeom(connectionContext);
            panPreviewMap.initMap(newGeom, FIELD__GEO_FIELD, buffer);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param   connectionContext  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public CidsBean createDefaultGeom(final ConnectionContext connectionContext) {
        final int srid = CrsTransformer.extractSridFromCrs(CismapBroker.getInstance().getSrs().getCode());
        final BoundingBox initialBoundingBox;
        initialBoundingBox = CismapBroker.getInstance().getMappingComponent().getMappingModel().getInitialBoundingBox();
        final Point centerPoint = initialBoundingBox.getGeometry(srid).getCentroid();

        final MetaClass geomMetaClass = ClassCacheMultiple.getMetaClass(
                CidsBeanSupport.DOMAIN_NAME,
                TABLE_GEOM,
                connectionContext);
        final CidsBean newGeom = geomMetaClass.getEmptyInstance(connectionContext).getBean();
        try {
            newGeom.setProperty(FIELD__GEO_FIELD, centerPoint);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
        return newGeom;
    }
}
